server:
  port: 8087

# Configuração do banco de dados
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: 23031990
  jpa:
    hibernate:
      ddl-auto: update # Estamos habilitando a atualização do banco de dados automaticamente quando fizermos alterações nas classes
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output: # Configuracao para habilitar as cores no prompt de comando, padrao Ansi
    ansi:
      enabled: Always

# Configuracao para habilitar os logs em niveis de detalhamento mais altos, o LOGBack é a biblioteca padrao do Spring
logging:
  level:
    com.ead: TRACE # Definicao do nivel de pacote, nesse caso, ead. Se tiver dois niveis definidos para o mesmo pacote, o Spring utilizara o nivel de maior detalhamento
    root: INFO # Definicao a nivel de aplicacao
    org.springframework.web: DEBUG # Definicao para ver as requisicoes e suas informacoes
    org.hibernate: INFO # Definicao para ver as informacoes do hibernate e de informacoes que forem processadas

ead:
  api:
    url:
      course: 'http://localhost:8082'